# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calc(object):
    def setupUi(self, calc):
        calc.setObjectName("calc")
        calc.resize(557, 452)
        calc.setSizeGripEnabled(True)
        calc.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(calc)
        self.gridLayout.setObjectName("gridLayout")
        self.value_0 = QtWidgets.QPushButton(calc)
        self.value_0.setObjectName("value_0")
        self.gridLayout.addWidget(self.value_0, 5, 0, 1, 1)
        self.add = QtWidgets.QPushButton(calc)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 1, 3, 1, 1)
        self.value_4 = QtWidgets.QPushButton(calc)
        self.value_4.setObjectName("value_4")
        self.gridLayout.addWidget(self.value_4, 2, 0, 2, 1)
        self.sub = QtWidgets.QPushButton(calc)
        self.sub.setObjectName("sub")
        self.gridLayout.addWidget(self.sub, 2, 3, 1, 1)
        self.value_2 = QtWidgets.QPushButton(calc)
        self.value_2.setObjectName("value_2")
        self.gridLayout.addWidget(self.value_2, 1, 1, 1, 1)
        self.value_3 = QtWidgets.QPushButton(calc)
        self.value_3.setObjectName("value_3")
        self.gridLayout.addWidget(self.value_3, 1, 2, 1, 1)
        self.value_9 = QtWidgets.QPushButton(calc)
        self.value_9.setObjectName("value_9")
        self.gridLayout.addWidget(self.value_9, 4, 2, 1, 1)
        self.value_1 = QtWidgets.QPushButton(calc)
        self.value_1.setObjectName("value_1")
        self.gridLayout.addWidget(self.value_1, 1, 0, 1, 1)
        self.value_7 = QtWidgets.QPushButton(calc)
        self.value_7.setObjectName("value_7")
        self.gridLayout.addWidget(self.value_7, 4, 0, 1, 1)
        self.div = QtWidgets.QPushButton(calc)
        self.div.setObjectName("div")
        self.gridLayout.addWidget(self.div, 4, 3, 1, 1)
        self.value_6 = QtWidgets.QPushButton(calc)
        self.value_6.setObjectName("value_6")
        self.gridLayout.addWidget(self.value_6, 2, 2, 2, 1)
        self.value_5 = QtWidgets.QPushButton(calc)
        self.value_5.setObjectName("value_5")
        self.gridLayout.addWidget(self.value_5, 2, 1, 2, 1)
        self.mul = QtWidgets.QPushButton(calc)
        self.mul.setObjectName("mul")
        self.gridLayout.addWidget(self.mul, 3, 3, 1, 1)
        self.calc_display = QtWidgets.QLCDNumber(calc)
        self.calc_display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calc_display.setSmallDecimalPoint(True)
        self.calc_display.setProperty("value", 0.0)
        self.calc_display.setObjectName("calc_display")
        self.gridLayout.addWidget(self.calc_display, 0, 0, 1, 4)
        self.value_8 = QtWidgets.QPushButton(calc)
        self.value_8.setObjectName("value_8")
        self.gridLayout.addWidget(self.value_8, 4, 1, 1, 1)
        self.clear_p = QtWidgets.QPushButton(calc)
        self.clear_p.setObjectName("clear_p")
        self.gridLayout.addWidget(self.clear_p, 5, 1, 1, 1)
        self.equals = QtWidgets.QPushButton(calc)
        self.equals.setObjectName("equals")
        self.gridLayout.addWidget(self.equals, 5, 3, 1, 1)
        self.clear_a = QtWidgets.QPushButton(calc)
        self.clear_a.setObjectName("clear_a")
        self.gridLayout.addWidget(self.clear_a, 5, 2, 1, 1)

        self.retranslateUi(calc)
        QtCore.QMetaObject.connectSlotsByName(calc)
        calc.setTabOrder(self.value_1, self.value_2)
        calc.setTabOrder(self.value_2, self.value_3)
        calc.setTabOrder(self.value_3, self.value_4)
        calc.setTabOrder(self.value_4, self.value_5)
        calc.setTabOrder(self.value_5, self.value_6)
        calc.setTabOrder(self.value_6, self.value_7)
        calc.setTabOrder(self.value_7, self.value_8)
        calc.setTabOrder(self.value_8, self.value_9)
        calc.setTabOrder(self.value_9, self.value_0)
        calc.setTabOrder(self.value_0, self.equals)
        calc.setTabOrder(self.equals, self.add)
        calc.setTabOrder(self.add, self.sub)
        calc.setTabOrder(self.sub, self.mul)
        calc.setTabOrder(self.mul, self.div)

    def retranslateUi(self, calc):
        _translate = QtCore.QCoreApplication.translate
        calc.setWindowTitle(_translate("calc", "Dialog"))
        self.value_0.setText(_translate("calc", "0"))
        self.add.setText(_translate("calc", "+"))
        self.value_4.setText(_translate("calc", "4"))
        self.sub.setText(_translate("calc", "-"))
        self.value_2.setText(_translate("calc", "2"))
        self.value_3.setText(_translate("calc", "3"))
        self.value_9.setText(_translate("calc", "9"))
        self.value_1.setText(_translate("calc", "1"))
        self.value_7.setText(_translate("calc", "7"))
        self.div.setText(_translate("calc", "/"))
        self.value_6.setText(_translate("calc", "6"))
        self.value_5.setText(_translate("calc", "5"))
        self.mul.setText(_translate("calc", "*"))
        self.value_8.setText(_translate("calc", "8"))
        self.clear_p.setText(_translate("calc", "C"))
        self.equals.setText(_translate("calc", "="))
        self.clear_a.setText(_translate("calc", "AC"))

